#!/usr/bin/env python3
"""Stage 2-4. Reads rc_prs.json, writes rc_results.md. READ ONLY."""
import json,os,re,math,statistics,datetime,collections
HERE=os.path.dirname(os.path.abspath(__file__))
PRS=json.load(open(os.path.join(HERE,"rc_prs.json")))
OUT=[]
def w(s=""): OUT.append(s)

# ---- surface ----
TRIV=re.compile(r"(package-lock\.json|poetry\.lock|\.lock$|next-env\.d\.ts)$")
def surf(p):
    if TRIV.search(p): return None
    return "backend" if p.startswith("backend/") else ("frontend" if p.startswith("frontend/") else None)
def csurf(pr):
    c=collections.Counter(s for s in map(surf,[f["path"] for f in (pr.get("files") or [])]) if s); d=sum(c.values())
    if d==0: return "neither"
    if c["backend"]/d>.60: return "backend-dominant"
    if c["frontend"]/d>.60: return "frontend-dominant"
    return "mixed"

# ---- treatment ----
KEYWORDS={"independent verification":r"independent(ly)?\s+verif",
 "clean-context / clean context":r"clean[\s-]context","adversarial":r"adversarial",
 "independent reviewer/review/pass":r"independent\s+(reviewer|review|check|pass|agent)",
 "second opinion":r"second\s+opinion","fresh agent / fresh eyes / fresh context":r"fresh\s+(sub-?\s?agent|agent|eyes|context)",
 "sub-agent verified":r"sub-?\s?agent\s+(verif|review|check|confirm)",
 "separate/another/second agent":r"(separate|another|second)\s+(sub-?\s?agent|agent)"}
KRE={k:re.compile(v,re.I) for k,v in KEYWORDS.items()}
NEG=re.compile(r"(no|not|never|without|didn'?t|did not|cannot|could not|couldn'?t|absent|skipped|disabled)\b[^.\n]{0,90}$",re.I)
ADV_INPUT=re.compile(r"adversarial[- ](injection|input|prompt|payload|suite|test|case|corpus|fixture|free-text|note|pin|probe)",re.I)
# Hand audit of all 43 auto-surviving matches; these describe something other than
# an independent verification pass on THIS PR's work. Reason recorded per PR.
HAND_EXCLUDE={195:"adversarial review was quota-blocked, never ran",
 201:"adversarial-review workflow explicitly skipped",259:"adversarial free-text is a test input",
 741:"adversarial note is a test fixture",202:"adversarial pin is a test name",
 863:"the adversarial review verified #847, not this PR",832:"'clean-context author' describes who wrote tests, not a verifier",
 191:"fixes findings from a review of #170, not a review of this PR"}
def txt(pr): return "\n".join([pr.get("body") or ""]+[(c.get("body") or "") for c in (pr.get("comments") or [])]+[(r.get("body") or "") for r in (pr.get("reviews") or [])])
def treat(pr):
    t=txt(pr); raw=[]; kept=[]
    for k,r in KRE.items():
        for m in r.finditer(t):
            raw.append(k)
            if k=="adversarial" and ADV_INPUT.search(t[m.start():m.end()+30]): continue
            if NEG.search(t[max(0,m.start()-100):m.start()].replace("\n"," ")): continue
            kept.append(k); break
    return sorted(set(raw)),sorted(set(kept))

FIX=re.compile(r"\b(fix(e[sd])?|fixing|bug|broken|regression|revert(ed|s)?|incorrect|wrong)\b",re.I)
H=datetime.timedelta(hours=72)
for pr in PRS:
    pr["_s"]=csurf(pr); pr["_raw"],pr["_kept"]=treat(pr)
    pr["_t_auto"]=bool(pr["_kept"]); pr["_t"]=bool(pr["_kept"]) and pr["number"] not in HAND_EXCLUDE
    pr["_paths"]=set(f["path"] for f in (pr.get("files") or []))
    pr["_nf"]=len(pr.get("files") or []); pr["_nl"]=(pr.get("additions") or 0)+(pr.get("deletions") or 0)
    pr["_dt"]=datetime.datetime.strptime(pr["mergedAt"],"%Y-%m-%dT%H:%M:%SZ")
PRS.sort(key=lambda p:p["_dt"])
def rw(pr,rf):
    for l in PRS:
        if l["_dt"]<=pr["_dt"] or l["_dt"]-pr["_dt"]>H or l["number"]==pr["number"]: continue
        if not (pr["_paths"]&l["_paths"]): continue
        if not rf: return 1
        s=(l.get("title") or "")+"\n"+(l.get("body") or "")
        if FIX.search(s) or re.search(r"#%d\b"%pr["number"],s): return 1
    return 0
for pr in PRS: pr["_a"]=rw(pr,False); pr["_f"]=rw(pr,True)
def vel(pr): return sum(1 for l in PRS if pr["_dt"]<l["_dt"]<=pr["_dt"]+H)

ORD=["backend-dominant","frontend-dominant","mixed","neither"]
def ci(ak,an,bk,bn):
    if min(ak,an-ak,bk,bn-bk)<5: return None
    pa,pb=ak/an,bk/bn; se=math.sqrt(pa*(1-pa)/an+pb*(1-pb)/bn); d=pa-pb
    return d,d-1.96*se,d+1.96*se

w("# Does independent verification reduce later rework? — ai-running-coach corpus")
w("\nGenerated by `rc_analyze.py` from `rc_prs.json`. READ ONLY: no writes to the target repo.\n")
w("## 0. Corpus")
w("- **%d merged PRs**, %s .. %s."%(len(PRS),PRS[0]["mergedAt"][:10],PRS[-1]["mergedAt"][:10]))
w("- Fetch path: `gh pr list --state merged --search merged:A..B` in 7-day windows. The single")
w("  `--limit 1000` bulk query returns **HTTP 502** (response too large); windowing avoids it.")
w("  Zero failed windows. `files` and `comments` come back populated in the list query, so no")
w("  per-PR `gh pr view` calls were needed.")
w("- files list present: %d/%d · >=1 comment: %d/%d · non-empty body: %d/%d"%(
  sum(1 for p in PRS if p.get("files")),len(PRS),sum(1 for p in PRS if p.get("comments")),len(PRS),
  sum(1 for p in PRS if (p.get("body") or "").strip()),len(PRS)))
w("\n## 1. Surface classification rule\n")
w("Derived from the real tree (`git/trees/HEAD?recursive=1`), which has exactly two code roots:")
w("`backend/` (FastAPI, alembic, 286 test files) and `frontend/` (Next.js).\n")
w("- `backend/**` -> backend; `frontend/**` -> frontend.")
w("- Everything else (`docs/`, `scripts/`, `*.md`, `Makefile`, `docker-compose.yml`, `.github/`)")
w("  is excluded from the denominator, not counted as either surface.")
w("- Trivial files excluded: `package-lock.json`, `poetry.lock`, `*.lock`, `next-env.d.ts`.")
w("- X-dominant if >60% of remaining files are X; both present but neither >60% -> `mixed`;")
w("  zero backend/frontend files -> `neither`.\n")
sc=collections.Counter(p["_s"] for p in PRS)
for k in ORD: w("- %-18s %3d  (%.1f%%)"%(k,sc[k],100*sc[k]/len(PRS)))
w("\n## 2. Treatment keywords and per-keyword hit counts\n")
w("Matched case-insensitively over PR body + issue comments + review bodies.\n")
w("| keyword | regex | raw PRs hit |")
w("|---|---|---|")
for k,r in KEYWORDS.items(): w("| %s | `%s` | %d |"%(k,r,sum(1 for p in PRS if k in p["_raw"])))
w("")
w("| stage | PRs treated |")
w("|---|---|")
w("| raw keyword match | %d |"%sum(1 for p in PRS if p["_raw"]))
w("| after auto-filters (negation, adversarial-*input*) | %d |"%sum(1 for p in PRS if p["_t_auto"]))
w("| **after hand audit of all %d survivors (final)** | **%d** |"%(sum(1 for p in PRS if p["_t_auto"]),sum(1 for p in PRS if p["_t"])))
w("")
w("Auto-filters: a match is dropped if preceded within 90 chars by a negation")
w("(`no|not|never|without|didn't|cannot|absent|skipped|disabled`) — this catches bodies that say")
w("*\"no clean-context sub-agent drove the end-to-end run\"* — or if `adversarial` is followed by")
w("`injection|input|prompt|payload|suite|test|case|corpus|fixture|free-text|note|pin|probe`, which")
w("is adversarial-input security testing, not an independent review.\n")
w("Every one of the auto-surviving matches was then read in context. Hand-excluded:\n")
for n,why in sorted(HAND_EXCLUDE.items()): w("- **#%d** — %s"%(n,why))
w("\n## 3. POWER CHECK — 2x2 cell counts (surface x treated)\n")
w("| surface | treated | untreated | total | verdict |")
w("|---|---|---|---|---|")
for s in ORD:
    g=[p for p in PRS if p["_s"]==s]; t=sum(1 for p in g if p["_t"])
    v="**UNDERPOWERED — this arm cannot answer the question**" if t<10 else "n>=10 treated"
    w("| %s | %d | %d | %d | %s |"%(s,t,len(g)-t,len(g),v))
w("\n**Only `backend-dominant` has enough treated PRs to compare at all.** frontend-dominant has")
w("exactly %d treated PR out of %d. No difference computed on that surface means anything, and none"%(
  sum(1 for p in PRS if p["_s"]=="frontend-dominant" and p["_t"]),sc["frontend-dominant"]))
w("is claimed below.\n")
w("## 4. Rework rates\n")
for lab,key in (("WITH the fix-filter","_f"),("WITHOUT the fix-filter (same-file within 72h alone)","_a")):
    w("### %s\n"%lab)
    if key=="_f":
        w("Fix signal on the later PR: title or body matches")
        w("`fix|fixes|fixed|fixing|bug|broken|regression|revert|incorrect|wrong`, **or** cites the earlier PR number.\n")
    w("| surface | treated n | rework | rate | untreated n | rework | rate | diff (t−u) | 95% CI |")
    w("|---|---|---|---|---|---|---|---|---|")
    for s in ORD:
        g=[p for p in PRS if p["_s"]==s]; t=[p for p in g if p["_t"]]; u=[p for p in g if not p["_t"]]
        tk=sum(p[key] for p in t); uk=sum(p[key] for p in u)
        c=ci(tk,len(t),uk,len(u)) if t and u else None
        if c: ds="%+.1f pp"%(100*c[0]); cs="[%+.1f, %+.1f] pp"%(100*c[1],100*c[2])
        else:
            ds="%+.1f pp"%(100*(tk/len(t)-uk/len(u))) if t and u else "n/a"
            cs="cell <5 — **no interval**; exact %d/%d vs %d/%d"%(tk,len(t),uk,len(u))
        w("| %s | %d | %d | %s | %d | %d | %s | %s | %s |"%(s,len(t),tk,
          "%.1f%%"%(100*tk/len(t)) if t else "n/a",len(u),uk,"%.1f%%"%(100*uk/len(u)) if u else "n/a",ds,cs))
    w("")
w("**The differences are positive: treated PRs are followed by rework MORE often.** Section 5")
w("shows why that is a size artifact rather than a finding about verification.\n")
w("## 5. Why the outcome measure does not work in this repo\n")
w("Rework rate rises monotonically with PR size, and the untreated arm is already near-saturated,")
w("so there is almost no headroom for a treatment to reduce it. backend-dominant only:\n")
w("| files changed | n | rework (fix-filtered) | rework (any) | median PRs merged in the next 72h |")
w("|---|---|---|---|---|")
bd=[p for p in PRS if p["_s"]=="backend-dominant"]
for lo,hi in [(1,1),(2,3),(4,6),(7,11),(12,20),(21,10**9)]:
    g=[p for p in bd if lo<=p["_nf"]<=hi]
    if not g: continue
    w("| %s | %d | %.1f%% | %.1f%% | %.0f |"%("%d-%d"%(lo,hi) if hi<10**9 else "%d+"%lo,len(g),
      100*sum(p["_f"] for p in g)/len(g),100*sum(p["_a"] for p in g)/len(g),statistics.median([vel(p) for p in g])))
w("\nA 1-file backend PR reworks 14%% of the time; a 21+-file one reworks 89%%. With a median of")
w("~%d PRs merging in any 72h window, \"a later PR touched one of my files within 3 days\" is close"%(
  int(statistics.median([vel(p) for p in bd]))))
w("to a measure of how many files a PR touched.\n")
w("Stratifying backend-dominant by size to hold that constant (fix-filtered):\n")
w("| files changed | treated | rate | untreated | rate | diff |")
w("|---|---|---|---|---|---|")
for lo,hi in [(1,3),(4,7),(8,14),(15,10**9)]:
    g=[p for p in bd if lo<=p["_nf"]<=hi]; t=[p for p in g if p["_t"]]; u=[p for p in g if not p["_t"]]
    lab="%d-%d"%(lo,hi) if hi<10**9 else "%d+"%lo
    if not t or not u: w("| %s | %d | n/a | %d | n/a | n/a |"%(lab,len(t),len(u))); continue
    tr=sum(p["_f"] for p in t)/len(t); ur=sum(p["_f"] for p in u)/len(u)
    w("| %s | %d/%d | %.1f%% | %d/%d | %.1f%% | %+.1f pp |"%(lab,sum(p["_f"] for p in t),len(t),100*tr,
      sum(p["_f"] for p in u),len(u),100*ur,100*(tr-ur)))
w("\nThe gap shrinks under stratification but does not vanish or reverse. Every stratum cell is")
w("small (treated n of 3, 4, 15, 10) and the untreated baseline is 47-87%, so no stratum can")
w("detect a reduction even if one exists.\n")
w("## 6. Selection effect (median size, treated vs untreated, within surface)\n")
w("| surface | treated n | med files | untreated n | med files | treated med lines | untreated med lines |")
w("|---|---|---|---|---|---|---|")
def med(x): return statistics.median(x) if x else float("nan")
for s in ORD:
    g=[p for p in PRS if p["_s"]==s]; t=[p for p in g if p["_t"]]; u=[p for p in g if not p["_t"]]
    w("| %s | %d | %s | %d | %.1f | %s | %.0f |"%(s,len(t),"%.1f"%med([p["_nf"] for p in t]) if t else "n/a",
      len(u),med([p["_nf"] for p in u]),"%.0f"%med([p["_nl"] for p in t]) if t else "n/a",med([p["_nl"] for p in u])))
w("\nOn backend-dominant, treated PRs are **%.1fx** the untreated median in files and **%.1fx** in lines."%(
  med([p["_nf"] for p in bd if p["_t"]])/med([p["_nf"] for p in bd if not p["_t"]]),
  med([p["_nl"] for p in bd if p["_t"]])/med([p["_nl"] for p in bd if not p["_t"]])))
w("Independent verification is applied to the big, risky changes. Combined with section 5, the")
w("+pp differences in section 4 are what that size gap predicts, not evidence about verification.\n")
w("## 7. What could not be determined\n")
w("- **Whether independent verification reduces rework on any surface.** backend-dominant is the")
w("  only powered arm and its outcome measure is confounded by size and near-saturated.")
w("- **Anything about the frontend.** 1 treated PR of %d."%sc["frontend-dominant"])
w("- **Anything about `mixed`.** 1 treated PR of %d."%sc["mixed"])
w("- **True treatment status.** Treatment is read from what the PR body claims. A PR that ran a")
w("  verification pass and did not write it down is counted untreated.")
open(os.path.join(HERE,"rc_results.md"),"w").write("\n".join(OUT)+"\n")
print("\n".join(OUT))
